name: Test arch dependencies

on:
  workflow_dispatch:

jobs:
  run-script:
    name: Run Script
    runs-on: ubuntu-latest

    steps:
      - name: Test dependencies
        run: ./tests/test-arch-dependencies.sh
