name: Test arch dependencies. Note that GitHub action do not currently support archlinux and this action will stay queued forever without a clear error.

on:
  workflow_dispatch:

jobs:
  run-script:
    name: Run Script
    runs-on: archlinux

    steps:
      - name: Install paru
        run: |
          sudo pacman -Sy --noconfirm base-devel
          git clone https://aur.archlinux.org/paru.git
          cd paru
          makepkg -si --noconfirm

      - name: Test dependencies
        run: ./tests/test-arch-dependencies.sh
