name: Test dependencies

on:
  workflow_dispatch:     # Allow running it manually.
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  test-arch-dependencies:
    name: Test Arch Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Test arch dependencies
        run: ./tests/test-arch-dependencies.sh

  test-ubuntu-dependencies:
    name: Test Ubuntu Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Test ubuntu dependencies
        run: ./tests/test-ubuntu-dependencies.sh

  test-macos-dependencies:
    name: Test MacOS Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Test macos dependencies
        run: ./tests/test-macos-dependencies.sh
        
  test-ternux-dependencies:
    name: Test Termux Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Test macos dependencies
        run: ./tests/test-termux-dependencies.sh

  test-fedora-dependencies:
    name: Test Fedora Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Test macos dependencies
        run: ./tests/test-fedora-dependencies.sh        
