name: Test dependencies

on:
  workflow_dispatch:

jobs:
  test-arch-dependencies:
    name: Test Arch Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Test arch dependencies
        run: ./tests/test-arch-dependencies.sh

  test-ubuntu-dependencies:
    name: Test Ubuntu Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Test ubuntu dependencies
        run: ./tests/test-ubuntu-dependencies.sh

  test-macos-dependencies:
    name: Test MacOS Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Test ubuntu dependencies
        run: ./tests/test-macos-dependencies.sh
        
